### ISSUE TITLE
looks cool and very nice,但我有一个疑问

### ISSUE THREAD

**Issue by BeanWei** [wanghaoxi3000/mcenter#1]
~~文章的分类不是应该建立超链吗，怎么把每个分类下的文章的URL获取呀？求不吝指教~~
看了你的博客，我看到了 分类下面映射的url，哇，突然觉得好强大，没懂是怎么做到的，
`def get_queryset(self):
        query_set = super().get_queryset()
        category = self.request.query_params.get('category',None)
        archive = self.request.query_params.get('archive', None)
        if category is not None:
            query_set = query_set.filter(category__slug=category)
        if archive is not None:
            if len(archive) != 6:
                raise ParseError
            query_set = query_set.filter(timestamp__year=archive[:4], timestamp__month=archive[4:6])
        return query_set`
是这段代码带来的操作，配合slug？

**Comment by wanghaoxi3000** [comment]
后端Django使用到了django-rest-framework框架, `get_queryset(self)`是这个框架中Viewset类视图获取queryset的方法, 这里通过重写这个方法, 通过从`self.request.query_params`这个属性中获取访问URL中的`category`和`archive`参数来过滤原始的queryset, 获得指定分类或时间存档下的文章.

流程差不多是这样的:
1. 假设有个分类叫`Python学习`, 创建后自动生成的slug为`Python_xue_xi`
2. 访问 blogsite.com/blog/articles/?category=Python_xue_xi
3. 进入到对应的`EntryViewSet`视图中, 在`get_queryset(self)`方法中获得`Python_xue_xi`这一参数来获取此分类下的文章

文章的URL获取这里也是用到了django-rest-framework的`HyperlinkedModelSerializer`基类, 使用此基类序列化的对象会自动生成`id`对应的URL, 也可以直接使用Django的`reverse`API来手动获取URL

可以直接看看django-rest-framework的文档, 讲的很详细.
http://www.django-rest-framework.org/
[ViewSets](http://www.django-rest-framework.org/api-guide/viewsets/#modelviewset)
[HyperlinkedRelatedField](http://www.django-rest-framework.org/api-guide/relations/#hyperlinkedrelatedfield)
