### ISSUE TITLE
还有一个问题就是MnaytoMany 下怎么建立slug？

### ISSUE THREAD

**Issue by BeanWei** [wanghaoxi3000/mcenter#2]

**Comment by wanghaoxi3000** [comment]
没太明白你的意思... 我这代码中slug都是自动生成的, 多对一和多对多关系对slug的生成都没影响. 
如果文章Entry和类别Category之间做成多对多关系的话, `Entry.objects.filter(category__slug=xxx_slug)` 这种筛选语句应该是同样有效的.

**Comment by BeanWei** [comment]
query_set.filter（）中多对多的slug 请求好像没用。。。

**Comment by wanghaoxi3000** [comment]
我测试了下多对多模型下`query_set.filter()`是有效的.
另外也可以通过` Category.objects.get(slug='xxx_slug').entry_set.all()`来得到指定分类下的文章

**Comment by BeanWei** [comment]
感谢！！！第一种方式是我自己搞错了，是可以的。第二种方式我试了，也同样是可以的。不得不说，Django跨表操作真的很强，大佬 你的操作也甚是🐮X吖。

**Comment by wanghaoxi3000** [comment]
哈哈 过奖了... 我哪算大佬啊 这块用的比较多而已啦
